matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++
            - cmake
            - cmake-data
            - make
          env: MATRIX_EVAL="CC=gcc && CXX=g++

script:
  - eval "${MATRIX_EVAL}"
  - mkdir build && cd build && cmake -G"Unix Makefiles" -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS_INIT="-Wall -Wextra" -DCMAKE_CXX_FLAGS_INIT="-Wall -Wextra" .. && make && cd ..
